### 1. Get latest BTC-USDT rate
GET {{server_address}}/api/btcusdt

### 2. Get BTC-USDT rate history
POST {{server_address}}/api/btcusdt
Content-Type: application/json; charset=UTF-8

{
  "since": "2022-06-11 12:00:00",
  "till": "2022-06-13 23:59:59",
  "page_number": 1,
  "page_size": 5
}


### 3. Get latest currencies to RUB rates
GET {{server_address}}/api/currencies

### 4. Get currencies to RUB rates history
POST {{server_address}}/api/currencies
Content-Type: application/json; charset=UTF-8

{
  "since": "2022-06-11",
  "till": "2022-06-12",
  "currency": "JPY",
  "page_number": 1,
  "page_size": 5
}


### 5. Get latest currencies to BTC rates
GET {{server_address}}/api/latest

### 6. Get currencies to BTC rates history
POST {{server_address}}/api/latest
Content-Type: application/json; charset=UTF-8

{
  "since": "2022-06-11 12:00:00",
  "till": "2022-06-13 23:59:59",
  "currency": "RUB",
  "page_number": 1,
  "page_size": 5
}
